### ISSUE TITLE
'U' mode is deprecated

### ISSUE THREAD

**Issue by xavier-j** [MatteoPS/EasyPrimer#1]
Hi there,
I got the following issue when running EasyPrimer on Linux:

/opt/Programs/EasyPrimer/EasyPrimer.py:97: DeprecationWarning: 'U' mode is deprecated
  with open(inputpath + genename_ext, "rU") as handle:

Is that concerning?

**Comment by MatteoPS** [comment]
Hi Xavier!

Thank you for the report.
The deprecation of the "U" mode in Python is not a big deal, the tool should work just fine.
Nevertheless I remove the "U" from the script to solve the Issue, I also tweak few more things to make everything run smooth.

Please download again the tool and try it out; I will be glad to help you if you find any other issue.
Thank you!
Have a great day
